name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ...
    - name: Build Docker image
      run: |
        docker build \
          --build-arg ENV_VARIABLES="DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }},\
            DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }},\
            DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }},\
            DJANGO_SECURE_SSL_REDIRECT=${{ secrets.DJANGO_SECURE_SSL_REDIRECT }},\
            DJANGO_SESSION_COOKIE_HTTPONLY=${{ secrets.DJANGO_SESSION_COOKIE_HTTPONLY }}" \
          -t gemesil/jobhawk:latest .
